# Player Plot Configuration
# Read more on the wiki:
# https://github.com/Whitescan/PlayerPlot/wiki/Configuration#configuring-configyml
Language file: en
Use /pplot root: false
Starting Plot Amount: 1
Maximum Plot Amount: 50
Plot Unit Size: 25
Plot pvp: true
Plot world blacklist:
  - example-world
Protection warning:
  particle: true
  sound: true
  message: true
# Database
Use database: false
host: localhost
port: 3306
database: myDatabase
username: myUsername
password: 'myPassword'
ssl: false
# Dynmap
Use dynmap: true
Use bluemap: true
Show Plot Markers by Default: true
