name: PlayerPlot
version: 1.20.0
main: de.whitescan.playerplot.PlayerPlot
api-version: 1.13
authors: [ sword7(Original), Whitescan(Maintainer) ]
description: A plugin that adds protected areas for player use.
load: POSTWORLD
softdepend: [ dynmap ]

commands:
  pplot:
    description: edit plots
  plot:
    description: edit plots
  toplot:
    description: teleport to plot
  playerplot:
    description: show plugin commands
  plotdeed:
    description: summon plot deeds
  writedeed:
    description: write plot deeds
  allplots:
    description: view all plots
  delplot:
    description: delete plot
  delplotconfirm:
    description: confirm delete plot
  delplotcancel:
    description: cancel delete plot

permissions:
  playerplot.*:
    description: grants all Player Plot permissions
    default: op
  playerplot.loot:
    description: grants access to the /plotdeed
    default: op
  playerplot.access:
    description: grants access to all player's plots
    default: op
  playerplot.teleport:
    description: grants access to teleportation commands
    default: op
  playerplot.reload:
    description: grants access to /playerplot reload
    default: op
  playerplot.write:
    description: grants access to /writedeed
    default: true
  playerplot.admin.*:
    description: grants all Player Plot admin permissions
    default: op
  playerplot.admin.view:
    descriotion: grants access to /allplots
    default: op
  playerplot.admin.delete:
    description: grants access to plot deletion commands
    default: op
  playerplot.plot.*:
    description: grants access to all plot commands
    default: true
  playerplot.plot.scan:
    description: grants access to /plot scan
    default: op
  playerplot.plot.claim:
    description: grants access to /plot claim
    default: op
  playerplot.plot.list:
    description: grants access to /plot list
    default: op
  playerplot.plot.flist:
    description: grants access to /plot flist
    default: op
  playerplot.plot.rename:
    description: grants access to /plot rename
    default: op
  playerplot.plot.free:
    description: grants access to /plot free
    default: op
  playerplot.plot.info:
    description: grants access to /plot info
    default: op
  playerplot.plot.trust:
    description: grants access to /plot trust
    default: op
  playerplot.plot.untrust:
    description: grants access to /plot untrust
    default: op
  playerplot.plot.upgrade:
    description: grants access to /plot upgrade
    default: op
  playerplot.plot.downgrade:
    description: grants access to /plot downgrade
    default: op
  playerplot.plot.setcenter:
    description: grants access to /plot setcenter
    default: op
  playerplot.plot.setspawn:
    description: grants access to /plot setspawn
    default: op
